const TransactionActionTypes = {
    GET_TRANSACTION : 'GET_TRANSACTION',
    ADD_CONTACT_TO_TRANSACTION : 'ADD_CONTACT_TO_TRANSACTION',
    REMOVE_CONTACT_FROM_TRANSACTION : 'REMOVE_CONTACT_FROM_TRANSACTION',
    GET_TRANSACTION_BY_ID : 'GET_TRANSACTION_BY_ID',
    GET_TRANSACTION_BY_NAME : 'GET_TRANSACTION_BY_NAME',
    GET_TRANSACTION_BY_LENDER : 'GET_TRANSACTION_BY_LENDER',
    UPDATE_TRANSACTION : 'UPDATE_TRANSACTION',
    UPDATE_TRANSACTION_BY_PROPERTY : 'UPDATE_TRANSACTION_BY_PROPERTY',
    CREATE_NEW_TRANSACTION : 'CREATE_NEW_TRANSACTION'
};


export default TransactionActionTypes;